return {
  "stevearc/conform.nvim",
  optional = true,
  opts = {
    formatters_by_ft = {
      ["css"] = { "prettier" },
      ["handlebars"] = { "prettier" },
      ["html"] = { "prettier" },
      ["go"] = { "gofumpt", "goimports" },
      ["graphql"] = { "prettier" },
      ["javascript"] = { "prettier" },
      ["javascriptreact"] = { "prettier" },
      ["json"] = { "jsonls" },
      ["jsonc"] = { "jsonls" },
      ["less"] = { "prettier" },
      ["markdown"] = { "prettier" },
      ["markdown.mdx"] = { "prettier" },
      ["python"] = { "black" },
      ["scss"] = { "prettier" },
      ["terraform"] = { "terraform_fmt" },
      ["terraform-vars"] = { "terraform_fmt" },
      ["tf"] = { "terraform_fmt" },
      ["typescript"] = { "prettier" },
      ["typescriptreact"] = { "prettier" },
      ["vue"] = { "prettier" },
      ["yaml"] = { "prettier" },
    },
  },
}
